// functions/api/send-invoice.js
// POST /api/send-invoice
// Body: {
//   student_id, course_id, email, name, language,
//   invoice: { invoice_number, customer_reference, subject, quantity, unit_price,
//              total_amount, currency, invoice_date, due_date },
//   pdf_base64
// }
//
// Sends one invoice email with a PDF attachment and logs the invoice in
// Supabase. The QR payment part is generated by the bank and embedded in
// the client-side PDF before this endpoint is called.

import {
  supabaseHeaders,
  requireAdminAuth,
  jsonResponse,
  errorResponse,
  withErrorHandling,
  parseJsonBody,
} from './_utils.js';

const NOTIFY_EMAILS = ['info@learningwithgioia.ch'];
const FROM_EMAIL = 'learning with gioia <hello@oiagi.org>';
const ALLOWED_LANGUAGES = ['de', 'en'];
const INVOICE_NUMBER_RE = /^LWG-\d{4}-\d{4}$/;
const INVOICE_STATUS_CANDIDATES = ['sent', 'pending', 'unpaid', 'open'];
const PENDING_STATUS_CANDIDATES = ['pending', 'unpaid', 'open', 'sent'];

function esc(str) {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function cleanFilenamePart(value, fallback) {
  return String(value || fallback)
    .trim()
    .replace(/[^a-z0-9._-]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function invoiceGreeting({ language, name, first_name, last_name, gender }) {
  if (language === 'en') return `Hello ${first_name || name || 'there'},`;
  if (gender === 'female' && last_name) return `Sehr geehrte Frau ${last_name}`;
  if (gender === 'male' && last_name) return `Sehr geehrter Herr ${last_name}`;
  const fullName = [first_name, last_name].filter(Boolean).join(' ') || name;
  return fullName ? `Guten Tag ${fullName}` : 'Sehr geehrte Damen und Herren';
}

function buildEmail({ language, name, first_name, last_name, gender, invoice }) {
  const isEN = language === 'en';
  const invoiceNo = invoice.invoice_number || '';
  const amount = `${Number(invoice.total_amount || 0).toFixed(2)} ${invoice.currency || 'CHF'}`;
  const subject = isEN
    ? `Invoice ${invoiceNo} · learning with gioia`
    : `Rechnung ${invoiceNo} · learning with gioia`;

  const greeting = invoiceGreeting({ language, name, first_name, last_name, gender });
  const courseLabel = invoice.subject || (isEN ? 'your course' : 'deinen Kurs');
  const dueDate = invoice.due_date ? formatDate(invoice.due_date, isEN ? 'en' : 'de') : '';
  const intro = isEN ? 'Thank you for learning with us.' : 'Vielen Dank, dass Sie mit uns lernen.';
  const invoiceLine = isEN
    ? `Attached you will find the invoice for ${courseLabel}.`
    : `Anbei finden Sie die Rechnung für ${courseLabel}.`;
  const paymentLine = dueDate
    ? isEN
      ? `You can pay it easily with the QR bill in the PDF. The payment is due by ${dueDate}.`
      : `Sie können sie bequem mit dem QR-Zahlteil im PDF begleichen. Fällig ist die Rechnung bis zum ${dueDate}.`
    : isEN
      ? 'You will find the payment details directly in the attached PDF.'
      : 'Die Zahlungsdetails finden Sie direkt im angehängten PDF.';
  const questionLine = isEN
    ? 'If anything looks unclear, just reply to this email.'
    : 'Falls etwas unklar ist, antworten Sie einfach direkt auf diese E-Mail.';
  const sign = isEN ? 'Warm regards,' : 'Herzliche Grüsse';

  const html = `<!DOCTYPE html>
<html lang="${isEN ? 'en' : 'de'}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f8fb;font-family:Georgia,serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f8fb;padding:40px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;max-width:600px;width:100%;">
        <tr>
          <td style="background:#1a1a1a;padding:32px 40px;">
            <p style="margin:0;color:#d6eaf8;font-family:Georgia,serif;font-size:13px;letter-spacing:0.2em;text-transform:uppercase;">learning with gioia</p>
          </td>
        </tr>
        <tr>
          <td style="padding:40px 40px 16px;">
            <p style="margin:0 0 24px;font-size:22px;font-weight:normal;color:#1a1a1a;font-family:Georgia,serif;">
              ${isEN ? 'Invoice' : 'Rechnung'} ${esc(invoiceNo)}
            </p>
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a;">${esc(greeting)}</p>
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#333;">
              ${esc(intro)}
            </p>
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#333;">
              ${esc(invoiceLine)}
            </p>
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#333;">
              ${isEN ? 'Amount' : 'Betrag'}: <strong>${esc(amount)}</strong><br>
              ${esc(paymentLine)}
            </p>
            <p style="margin:0 0 24px;font-size:15px;line-height:1.7;color:#333;">${esc(questionLine)}</p>
            <p style="margin:0 0 4px;font-size:15px;line-height:1.7;color:#333;">${esc(sign)}</p>
            <p style="margin:0;font-size:15px;line-height:1.7;color:#333;">Gioia</p>
          </td>
        </tr>
        <tr>
          <td style="padding:24px 40px 32px;border-top:1px solid #eee;">
            <p style="margin:0;font-size:13px;color:#aaa;line-height:1.6;">
              <a href="https://learningwithgioia.ch" style="color:#aaa;">learningwithgioia.ch</a>
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

  return { subject, html };
}

function formatDate(value, language) {
  if (!value) return '';
  const date = new Date(value + 'T12:00:00');
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString(language === 'en' ? 'en-GB' : 'de-CH', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
}

function validate(body) {
  if (!body.student_id) return 'Missing student_id';
  if (!body.course_id) return 'Missing course_id';
  if (!body.email || typeof body.email !== 'string') return 'Missing email';
  if (!ALLOWED_LANGUAGES.includes(body.language)) return 'language must be one of: de, en';
  if (!body.pdf_base64 || typeof body.pdf_base64 !== 'string') return 'pdf_base64 is required';
  const inv = body.invoice || {};
  if (!inv.invoice_number) return 'Missing invoice_number';
  if (!INVOICE_NUMBER_RE.test(inv.invoice_number)) {
    return 'invoice_number must use the format LWG-YYYY-0001';
  }
  if (!inv.total_amount || Number(inv.total_amount) <= 0) return 'Missing total_amount';
  return null;
}

async function invoiceNumberExists(env, invoiceNumber) {
  const res = await fetch(
    `${env.SUPABASE_URL}/rest/v1/invoices?invoice_number=eq.${encodeURIComponent(invoiceNumber)}&select=id&limit=1`,
    { headers: supabaseHeaders(env.SUPABASE_SERVICE_KEY) }
  );
  if (!res.ok) {
    console.error('Invoice number lookup failed:', await res.text());
    return false;
  }
  const rows = await res.json();
  return rows.length > 0;
}

async function updateInvoiceStatus(env, invoiceId, status) {
  if (!invoiceId) return;
  const res = await fetch(`${env.SUPABASE_URL}/rest/v1/invoices?id=eq.${invoiceId}`, {
    method: 'PATCH',
    headers: supabaseHeaders(env.SUPABASE_SERVICE_KEY),
    body: JSON.stringify({ status }),
  });
  if (!res.ok) {
    console.error(`Invoice status update failed for ${invoiceId}:`, await res.text());
  }
}

async function logInvoice(env, body, statusCandidates = INVOICE_STATUS_CANDIDATES) {
  const inv = body.invoice || {};
  const basePayload = {
    student_id: body.student_id,
    course_id: body.course_id,
    company_id: null,
    invoice_number: inv.invoice_number,
    total_amount: Number(inv.total_amount),
    currency: inv.currency || 'CHF',
    issued_date: inv.invoice_date || new Date().toISOString().slice(0, 10),
  };

  let lastError = '';
  for (const status of statusCandidates) {
    const res = await fetch(`${env.SUPABASE_URL}/rest/v1/invoices`, {
      method: 'POST',
      headers: {
        ...supabaseHeaders(env.SUPABASE_SERVICE_KEY),
        Prefer: 'return=representation',
      },
      body: JSON.stringify({ ...basePayload, status }),
    });

    if (res.ok) {
      const rows = await res.json().catch(() => []);
      return rows[0] || null;
    }

    lastError = await res.text();
    if (!lastError.includes('invoices_status_check')) break;
  }

  console.error('Invoice log failed:', lastError);
  const err = new Error('Invoice could not be recorded. Email was not sent.');
  err.statusCode = 400;
  err.userMessage = 'Invoice could not be recorded. Email was not sent.';
  throw err;
}

export const onRequestPost = withErrorHandling(async ({ request, env }) => {
  const { RESEND_API_KEY } = env;

  const authErr = await requireAdminAuth(request, env);
  if (authErr) return authErr;

  if (!RESEND_API_KEY) {
    console.error('RESEND_API_KEY not configured');
    return errorResponse('Email service not configured', 500);
  }

  const { body, error } = await parseJsonBody(request);
  if (error) return error;

  const invalid = validate(body || {});
  if (invalid) return errorResponse(invalid, 400);

  if (await invoiceNumberExists(env, body.invoice.invoice_number)) {
    return errorResponse('Invoice number already exists. Please reopen the invoice modal.', 409);
  }

  const invoiceRecord = await logInvoice(env, body, PENDING_STATUS_CANDIDATES);

  const { subject, html } = buildEmail({
    language: body.language,
    name: body.name || '',
    first_name: body.first_name || '',
    last_name: body.last_name || '',
    gender: body.gender || '',
    invoice: body.invoice,
  });
  const filename = `${body.language === 'en' ? 'invoice' : 'rechnung'}-${cleanFilenamePart(
    body.invoice.invoice_number,
    'lwg'
  )}.pdf`;

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${RESEND_API_KEY}`,
    },
    body: JSON.stringify({
      from: FROM_EMAIL,
      to: [body.email],
      reply_to: NOTIFY_EMAILS,
      subject,
      html,
      attachments: [
        {
          filename,
          content: body.pdf_base64,
        },
      ],
    }),
  });

  if (!res.ok) {
    console.error(`Invoice email failed for ${body.email}:`, await res.text());
    return errorResponse('Invoice email failed', 502);
  }

  await updateInvoiceStatus(env, invoiceRecord?.id, 'sent');
  if (invoiceRecord) invoiceRecord.status = 'sent';

  return jsonResponse({ success: true, invoice: invoiceRecord });
}, 'send-invoice');
