// functions/api/send-invoice.js
// POST /api/send-invoice
// Body: {
//   student_id, course_id, email, name, language,
//   invoice: { invoice_number, customer_reference, subject, quantity, unit_price,
//              total_amount, currency, invoice_date, due_date },
//   pdf_base64
// }
//
// Sends one invoice email with a PDF attachment and logs the invoice in
// Supabase. The QR payment part is generated by the bank and embedded in
// the client-side PDF before this endpoint is called.

import {
  requireAdminAuth,
  jsonResponse,
  errorResponse,
  withErrorHandling,
  parseJsonBody,
} from './_utils.js';
import {
  INVOICE_NUMBER_RE,
  PENDING_STATUS_CANDIDATES,
  FINALISED_STATUSES,
  findInvoiceByNumber,
  updateInvoiceStatus,
  archiveInvoicePdf,
  logInvoice,
} from './_invoices.js';

const NOTIFY_EMAILS = ['info@learningwithgioia.ch'];
const FROM_EMAIL = 'learning with gioia <hello@oiagi.org>';
const ALLOWED_LANGUAGES = ['de', 'en'];

function esc(str) {
  if (str === null || str === undefined) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function cleanFilenamePart(value, fallback) {
  return String(value || fallback)
    .trim()
    .replace(/[^a-z0-9._-]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function surnameFromName(name) {
  const parts = String(name || '')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  return parts.length > 1 ? parts[parts.length - 1] : '';
}

function fullNameFromParts(firstName, lastName, fallbackName = '') {
  return [firstName, lastName].filter(Boolean).join(' ') || fallbackName;
}

function invoiceGreeting({ language, name, first_name, last_name, gender }) {
  if (language === 'en') return `Hello ${first_name || name || 'there'},`;
  if (first_name) return `Liebe ${first_name}`;
  const surname = last_name || surnameFromName(name);
  if (gender === 'female' && surname) return `Liebe Frau ${surname}`;
  if (gender === 'male' && surname) return `Lieber Herr ${surname}`;
  const fullName = fullNameFromParts(first_name, last_name, name);
  return fullName ? `Guten Tag ${fullName}` : 'Guten Tag';
}

function buildEmail({ language, name, first_name, last_name, gender, invoice }) {
  const isEN = language === 'en';
  const invoiceNo = invoice.invoice_number || '';
  const amount = `${Number(invoice.total_amount || 0).toFixed(2)} ${invoice.currency || 'CHF'}`;
  const subject = isEN
    ? `Invoice ${invoiceNo} · learning with gioia`
    : `Rechnung ${invoiceNo} · learning with gioia`;

  const greeting = invoiceGreeting({ language, name, first_name, last_name, gender });
  const courseLabel = invoice.subject || (isEN ? 'your course' : 'deinen Kurs');
  const dueDate = invoice.due_date ? formatDate(invoice.due_date, isEN ? 'en' : 'de') : '';
  const intro = isEN ? 'Thank you for learning with us.' : 'Danke, dass du mit uns lernst.';
  const invoiceLine = isEN
    ? `Attached you will find the invoice for ${courseLabel}.`
    : `Anbei findest du die Rechnung für ${courseLabel}.`;
  const paymentLine = dueDate
    ? isEN
      ? `You can pay it easily with the QR bill in the PDF. The payment is due by ${dueDate}.`
      : `Du kannst sie bequem mit dem QR-Zahlteil im PDF begleichen. Fällig ist die Rechnung bis zum ${dueDate}.`
    : isEN
      ? 'You will find the payment details directly in the attached PDF.'
      : 'Die Zahlungsdetails findest du direkt im angehängten PDF.';
  const questionLine = isEN
    ? 'If anything looks unclear, just reply to this email.'
    : 'Falls etwas unklar ist, antworte einfach direkt auf diese E-Mail.';
  const sign = isEN ? 'Warm regards,' : 'Herzliche Grüsse';

  const html = `<!DOCTYPE html>
<html lang="${isEN ? 'en' : 'de'}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f8fb;font-family:Georgia,serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f8fb;padding:40px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;max-width:600px;width:100%;">
        <tr>
          <td style="background:#1a1a1a;padding:32px 40px;">
            <p style="margin:0;color:#d6eaf8;font-family:Georgia,serif;font-size:13px;letter-spacing:0.2em;text-transform:uppercase;">learning with gioia</p>
          </td>
        </tr>
        <tr>
          <td style="padding:40px 40px 16px;">
            <p style="margin:0 0 24px;font-size:22px;font-weight:normal;color:#1a1a1a;font-family:Georgia,serif;">
              ${isEN ? 'Invoice' : 'Rechnung'} ${esc(invoiceNo)}
            </p>
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a;">${esc(greeting)}</p>
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#333;">
              ${esc(intro)}
            </p>
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#333;">
              ${esc(invoiceLine)}
            </p>
            <p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#333;">
              ${isEN ? 'Amount' : 'Betrag'}: <strong>${esc(amount)}</strong><br>
              ${esc(paymentLine)}
            </p>
            <p style="margin:0 0 24px;font-size:15px;line-height:1.7;color:#333;">${esc(questionLine)}</p>
            <p style="margin:0 0 4px;font-size:15px;line-height:1.7;color:#333;">${esc(sign)}</p>
            <p style="margin:0;font-size:15px;line-height:1.7;color:#333;">Gioia</p>
          </td>
        </tr>
        <tr>
          <td style="padding:24px 40px 32px;border-top:1px solid #eee;">
            <p style="margin:0;font-size:13px;color:#aaa;line-height:1.6;">
              <a href="https://learningwithgioia.ch" style="color:#aaa;">learningwithgioia.ch</a>
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

  return { subject, html };
}

function formatDate(value, language) {
  if (!value) return '';
  const date = new Date(value + 'T12:00:00');
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString(language === 'en' ? 'en-GB' : 'de-CH', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
}

function validate(body) {
  if (!body.student_id) return 'Missing student_id';
  if (!body.course_id) return 'Missing course_id';
  if (!body.email || typeof body.email !== 'string') return 'Missing email';
  if (!ALLOWED_LANGUAGES.includes(body.language)) return 'language must be one of: de, en';
  if (!body.pdf_base64 || typeof body.pdf_base64 !== 'string') return 'pdf_base64 is required';
  const inv = body.invoice || {};
  if (!inv.invoice_number) return 'Missing invoice_number';
  if (!INVOICE_NUMBER_RE.test(inv.invoice_number)) {
    return 'invoice_number must use the format LWG-YYYY-0001';
  }
  if (!inv.total_amount || Number(inv.total_amount) <= 0) return 'Missing total_amount';
  return null;
}

export const onRequestPost = withErrorHandling(async ({ request, env }) => {
  const { RESEND_API_KEY } = env;

  const authErr = await requireAdminAuth(request, env);
  if (authErr) return authErr;

  if (!RESEND_API_KEY) {
    console.error('RESEND_API_KEY not configured');
    return errorResponse('Email service not configured', 500);
  }

  const { body, error } = await parseJsonBody(request);
  if (error) return error;

  const invalid = validate(body || {});
  if (invalid) return errorResponse(invalid, 400);

  // Reuse a record that was previously logged when the PDF was downloaded, so
  // downloading and then sending the same invoice does not create a duplicate.
  // A genuine duplicate (already emailed/paid) is still refused.
  const existing = await findInvoiceByNumber(env, body.invoice.invoice_number);
  if (existing && FINALISED_STATUSES.has(existing.status)) {
    return errorResponse('Invoice number already exists. Please reopen the invoice modal.', 409);
  }

  const invoiceRecord = existing || (await logInvoice(env, body, PENDING_STATUS_CANDIDATES));

  const { subject, html } = buildEmail({
    language: body.language,
    name: body.name || '',
    first_name: body.first_name || '',
    last_name: body.last_name || '',
    gender: body.gender || '',
    invoice: body.invoice,
  });
  const filename = `${body.language === 'en' ? 'invoice' : 'rechnung'}-${cleanFilenamePart(
    body.invoice.invoice_number,
    'lwg'
  )}.pdf`;

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${RESEND_API_KEY}`,
    },
    body: JSON.stringify({
      from: FROM_EMAIL,
      to: [body.email],
      reply_to: NOTIFY_EMAILS,
      subject,
      html,
      attachments: [
        {
          filename,
          content: body.pdf_base64,
        },
      ],
    }),
  });

  if (!res.ok) {
    console.error(`Invoice email failed for ${body.email}:`, await res.text());
    return errorResponse('Invoice email failed', 502);
  }

  await updateInvoiceStatus(env, invoiceRecord?.id, 'sent');
  if (invoiceRecord) invoiceRecord.status = 'sent';

  await archiveInvoicePdf(env, body.invoice.invoice_number, body.pdf_base64).catch((err) => {
    console.error('Invoice archive unexpected error:', err);
  });

  return jsonResponse({ success: true, invoice: invoiceRecord });
}, 'send-invoice');
