// functions/api/send-invoice.js
// POST /api/send-invoice
// Body: {
//   student_id, course_id, email, name, language,
//   invoice: { invoice_number, customer_reference, subject, quantity, unit_price,
//              total_amount, currency, invoice_date, due_date },
//   pdf_base64
// }
//
// Sends one invoice email with a PDF attachment and logs the invoice in
// Supabase. The QR payment part is generated by the bank and embedded in
// the client-side PDF before this endpoint is called.

import {
  requireAdminAuth,
  jsonResponse,
  errorResponse,
  withErrorHandling,
  parseJsonBody,
} from './_utils.js';
import {
  INVOICE_NUMBER_RE,
  PENDING_STATUS_CANDIDATES,
  FINALISED_STATUSES,
  findInvoiceByNumber,
  updateInvoiceStatus,
  archiveInvoicePdf,
  logInvoice,
} from './_invoices.js';
import { sendResendEmail } from './_email.js';
import {
  esc,
  cleanFilenamePart,
  formatDate,
  invoiceGreeting,
  emailShell,
  bodyParagraph,
} from './_invoice-email.js';

const NOTIFY_EMAILS = ['info@learningwithgioia.ch'];
const ALLOWED_LANGUAGES = ['de', 'en'];

function buildEmail({ language, name, first_name, last_name, gender, invoice }) {
  const isEN = language === 'en';
  const invoiceNo = invoice.invoice_number || '';
  const amount = `${Number(invoice.total_amount || 0).toFixed(2)} ${invoice.currency || 'CHF'}`;
  const subject = isEN
    ? `Invoice ${invoiceNo} · learning with gioia`
    : `Rechnung ${invoiceNo} · learning with gioia`;

  const greeting = invoiceGreeting({ language, name, first_name, last_name, gender });
  const courseLabel = invoice.subject || (isEN ? 'your course' : 'deinen Kurs');
  const dueDate = invoice.due_date ? formatDate(invoice.due_date, isEN ? 'en' : 'de') : '';
  const intro = isEN ? 'Thank you for learning with us.' : 'Danke, dass du mit uns lernst.';
  const invoiceLine = isEN
    ? `Attached you will find the invoice for ${courseLabel}.`
    : `Anbei findest du die Rechnung für ${courseLabel}.`;
  const paymentLine = dueDate
    ? isEN
      ? `You can pay it easily with the QR bill in the PDF. The payment is due by ${dueDate}.`
      : `Du kannst sie bequem mit dem QR-Zahlteil im PDF begleichen. Fällig ist die Rechnung bis zum ${dueDate}.`
    : isEN
      ? 'You will find the payment details directly in the attached PDF.'
      : 'Die Zahlungsdetails findest du direkt im angehängten PDF.';
  const questionLine = isEN
    ? 'If anything looks unclear, just reply to this email.'
    : 'Falls etwas unklar ist, antworte einfach direkt auf diese E-Mail.';
  const sign = isEN ? 'Warm regards,' : 'Herzliche Grüsse';

  const bodyHtml = [
    `<p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#1a1a1a;">${esc(greeting)}</p>`,
    bodyParagraph(intro),
    bodyParagraph(invoiceLine),
    `<p style="margin:0 0 18px;font-size:15px;line-height:1.7;color:#333;">
      ${isEN ? 'Amount' : 'Betrag'}: <strong>${esc(amount)}</strong><br>
      ${esc(paymentLine)}
    </p>`,
    bodyParagraph(questionLine, '0 0 24px'),
    bodyParagraph(sign, '0 0 4px'),
    bodyParagraph('Gioia', '0'),
  ].join('\n');

  return {
    subject,
    html: emailShell({
      language,
      title: `${isEN ? 'Invoice' : 'Rechnung'} ${invoiceNo}`,
      bodyHtml,
    }),
  };
}

function validate(body) {
  if (!body.student_id) return 'Missing student_id';
  if (!body.course_id) return 'Missing course_id';
  if (!body.email || typeof body.email !== 'string') return 'Missing email';
  if (!ALLOWED_LANGUAGES.includes(body.language)) return 'language must be one of: de, en';
  if (!body.pdf_base64 || typeof body.pdf_base64 !== 'string') return 'pdf_base64 is required';
  const inv = body.invoice || {};
  if (!inv.invoice_number) return 'Missing invoice_number';
  if (!INVOICE_NUMBER_RE.test(inv.invoice_number)) {
    return 'invoice_number must use the format LWG-YYYY-0001';
  }
  if (!inv.total_amount || Number(inv.total_amount) <= 0) return 'Missing total_amount';
  return null;
}

export const onRequestPost = withErrorHandling(async ({ request, env }) => {
  const { RESEND_API_KEY } = env;

  const authErr = await requireAdminAuth(request, env);
  if (authErr) return authErr;

  if (!RESEND_API_KEY) {
    console.error('RESEND_API_KEY not configured');
    return errorResponse('Email service not configured', 500);
  }

  const { body, error } = await parseJsonBody(request);
  if (error) return error;

  const invalid = validate(body || {});
  if (invalid) return errorResponse(invalid, 400);

  // Reuse a record that was previously logged when the PDF was downloaded, so
  // downloading and then sending the same invoice does not create a duplicate.
  // A genuine duplicate (already emailed/paid) is still refused.
  const existing = await findInvoiceByNumber(env, body.invoice.invoice_number);
  if (existing && FINALISED_STATUSES.has(existing.status)) {
    return errorResponse('Invoice number already exists. Please reopen the invoice modal.', 409);
  }

  const invoiceRecord = existing || (await logInvoice(env, body, PENDING_STATUS_CANDIDATES));

  const { subject, html } = buildEmail({
    language: body.language,
    name: body.name || '',
    first_name: body.first_name || '',
    last_name: body.last_name || '',
    gender: body.gender || '',
    invoice: body.invoice,
  });
  const filename = `${body.language === 'en' ? 'invoice' : 'rechnung'}-${cleanFilenamePart(
    body.invoice.invoice_number,
    'lwg'
  )}.pdf`;

  const res = await sendResendEmail(RESEND_API_KEY, {
    to: [body.email],
    reply_to: NOTIFY_EMAILS,
    subject,
    html,
    attachments: [
      {
        filename,
        content: body.pdf_base64,
      },
    ],
  });

  if (!res.ok) {
    console.error(`Invoice email failed for ${body.email}:`, await res.text());
    return errorResponse('Invoice email failed', 502);
  }

  await updateInvoiceStatus(env, invoiceRecord?.id, 'sent');
  if (invoiceRecord) invoiceRecord.status = 'sent';

  await archiveInvoicePdf(env, body.invoice.invoice_number, body.pdf_base64).catch((err) => {
    console.error('Invoice archive unexpected error:', err);
  });

  return jsonResponse({ success: true, invoice: invoiceRecord });
}, 'send-invoice');
